### PR TITLE
Update mesos.yml

### PR DESCRIPTION
**Pull request by hectork01**

### CODE REVIEW

**Comment by rjeczalik** [comment]
I tried this one - it did not work for me for some reason (last error I remember it was complaining it can't elect a leader while accessing Marathon UI).

What about the official DC/OS stack? They provide a Cloudformation stack template:

https://downloads.dcos.io/dcos/stable/aws.html

Which we could apply with:

https://www.terraform.io/docs/providers/aws/r/cloudformation_stack.html

**Comment by hectork01** [comment]
@rjeczalik , Have you checked the original stack that @sibblegp submitted?, just to know if the error is because of this update that I did.

**Comment by sibblegp** [comment]
I know that my stack worked.  Not sure what happened.

**Comment by sibblegp** [comment]
Ok, apparently Marathon is now broken.  Something must have changed in the version installed.  I believe this was the guide that I used: https://www.digitalocean.com/community/tutorials/how-to-configure-a-production-ready-mesosphere-cluster-on-ubuntu-14-04

**Pull request closed without merging**
