### PR TITLE
Updated Mesos.yml

### PR DESCRIPTION
**Pull request by hectork01**

### CODE REVIEW

**Comment by szkl** [comment]
This is already submitted in https://github.com/koding/stacks/pull/1.

**Comment by hectork01** [comment]
This is also an updated version after @gokmen  and @rjeczalik suggestions.

**Comment by szkl** [comment]
Please pull changes in `master` and rename the file as `mesos.yml`.

**Comment by hectork01** [comment]
Done it, I'll close this request.

**Pull request closed without merging**
